#include "sys/time.h"
long total;
long decomp_onepass;
long process_data;
long idct_islow;
long ycc_rgb_conv;
long sep1_upsample;
long decode_mcu1;
long forward_dct;
long quant;
long conv;
long enc_mcu;
long create_comp;
long fdct_islow;
long rgb_ycc_st;
long rgb_ycc_c;
long jinit;
long sep_downs;
struct timeval start,end;